### PR TITLE
Marketing SMS trying again

### PR DESCRIPTION
**Pull request by glzr-dev**

### CODE REVIEW

**Comment by thelaurence** [comment]
I was only able to get the MarketingMessageTest (and all the other tests) to work on my local machine when I moved the tests directory so that it was a sub-directory of the src folder. When I did that all the tests passed, but I can't get the Travis CI build to work so I'm just submitting a pull request without the test file. MarketingMessage.php is working as expected for me. I'm sure it's just something simple that I'm missing, but I'm unfamiliar with how the Travis system works so I need a little direction.

**Comment by vood** [comment]
Please check unit test failures

**Comment by glzr-dev** [comment]
OK I think I fixed the problem, but the Travis build hasn't run again yet.

**Comment by glzr-dev** [comment]
@vood It took me a while but I finally got around to fixing the build errors on this PR.

**Comment by vood** [comment]
:+1:

**Pull request merged**
