### PR TITLE
Account APIs / Lazy Loading

### PR DESCRIPTION
**Pull request by CarsonF**
- Added most Account APIs (non-POST)
- Account APIs return entity objects so the user doesn't have to guess at array keys
- Guzzle client is created when needed, not when Nexmo client is created
- Service classes are created on-demand as well via a little bit of magic. Everything is type-hinted with phpdoc properties
- Everything is tested

P.S. Sorry for the monolithic PR. I intended to fork at first, but if you are willing to maintain this repo all the better.

### CODE REVIEW

**Comment by CarsonF** [comment]
Oh and BC has been maintained! :smile:

**Comment by glennjacobs** [comment]
This looks like an excellent update, only just discovered this package myself.

However, having used your fork I notice it's using "https://rest.nexmo.com/" which doesn't appear to work. Should be "https://api.nexmo.com/"

**Comment by CarsonF** [comment]
Thanks! I know there's a bunch of forks of the old crappy code, I was hoping to avoid that with this new one. If needed I'll think about maintaining this though. 

https://rest.nexmo.com seemed to work for me and _most_ of their documentation mentions that instead of https://api.nexmo.com. But from experience their documentation isn't completely up to date. I'll take your word for it though :)

**Comment by vood** [comment]
@CarsonF great job. Sorry I haven't seen the notification about the pull request. Let me code-review it first.

**Comment by CarsonF** [comment]
@vood No worries! Sure thing :) I made a couple changes to my fork's master branch, I'll cherry pick them to this PR.

**Comment by vood** [comment]
@CarsonF unfortunately we do need to have a separate base_url for each service as https://rest.nexmo.com does not support all the api features.

**Comment by CarsonF** [comment]
Hehe yeah I figured that out.

**Comment by vood** [comment]
Awesome man! Merged @CarsonF

**Comment by CarsonF** [comment]
Whoop! I'm going to PR a couple more things then after lunch!

**Comment by vood** [comment]
:+1:

**Pull request merged**
